version: "3"

services:
  laravel-a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet
    ports:
      - "9091:80"

    environment:
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal # or the IP of your Docker host
      DB_PORT: 3307
      DB_DATABASE: wallet
      DB_USERNAME: root
      DB_PASSWORD: 123456
    volumes:
      - .:/var/www/html





version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-DB
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html

    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-server
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    depends_on:
      - mysql
